### ISSUE TITLE
[Potential bug] League standing

### ISSUE THREAD

**Issue by Svetoslav11** [fplbot/fplbot#342] opened 2023-10-24 11:31 UTC
Currently, the league where I participate has 57 managers. After the game week finishes the bot displays only the first 50 managers. I couldn't find the endpoint for that to check if it's expected.

**Comment by johnkors** [comment] 2023-10-24 11:57
The bot only supports the top 50 of any league, I'm afraid. That's for any notification, not only the standings. Some leagues have thousands of members, so the cap is at 50 to reduce the workload. It's the same as the pagination of the official FPL pages.

Closing, as this is as intended.

**Closed by johnkors** 2023-10-24 11:57 UTC
